# Generated by Django 2.2.2 on 2020-01-25 16:32

from django.db import migrations, models
import django.db.models.deletion
import hiring.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('resume_file_name', models.FileField(upload_to=hiring.models.document_directory_path)),
                ('status', models.CharField(choices=[('Submit', 'Submit'), ('Review', 'Review'), ('Interview', 'Interview'), ('Hired', 'Hired')], default='Submit', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application_Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Application_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Application_Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Application_Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.Candidate')),
            ],
        ),
    ]
