# Generated by Django 2.2.2 on 2020-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('Submit', 'Submit'), ('Review', 'Review'), ('Interview', 'Interview'), ('Hired', 'Hired')], default='Submit', max_length=10),
        ),
    ]
